### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by unknooly** [sapic/avatarcropper#28]
Website shows initial page and all, but after selecting a photo it doesn't load it.

**Comment by LazySolitude** [comment]
Adding to this.
The image is actually loaded but the  <label class="bigOverlay" for="openInput" style="cursor: pointer; text-align: center;">Drag a File Here<br>Or Click to Select</label> wont disappear. 

Removing it will make the site function but it wont render.
caught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object.apply (<anonymous>:8696:43)
    at Object.outputHandler [as apply] (<anonymous>:366:36)
    at x.drawImage (https://avatarcropper.com/index.5b4b47d2.js:1:15758)
    at _.getFrameURLs (https://avatarcropper.com/index.5b4b47d2.js:1:46952)
    at _.render (https://avatarcropper.com/index.5b4b47d2.js:1:44502)
    at F.renderCroppedImage (https://avatarcropper.com/index.5b4b47d2.js:1:59452)
    at Y.renderCroppedImage (https://avatarcropper.com/index.5b4b47d2.js:1:93444)
    at HTMLButtonElement.c (https://avatarcropper.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:9405)

**Comment by apprehensions** [comment]
same

**Comment by TheOddball** [comment]
Fixed by TrueCarry

**Comment by apprehensions** [comment]
it's still broken

**Comment by SethanJoseph** [comment]
Seems to a Firefox issue.
